version: '3'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  # post gis enabled postgres
  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile-dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - ALLOW_IP_RANGE=172.18.0.0/16
      - POSTGRES_PASSWORD=mysecretpass
      - DB_NAME=product
      - POSTGRES_USER=product
      - DB_USER=product
      - DB_PASS=mysecretpass
    ports:
      - "5432:5432"

  # django based web server
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=mysecretpass
      - POSTGRES_DB=product
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    logging:
      options:
        max-size: "200m"
        max-file: "4"
#      - "27017:27017"

# Redis for memcache
  redis:
    image: redis:3.2.9
    hostname: redis

# RabbitMQ - queue
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - DEFAULT_USER=guest
      - DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"  # here, we can access rabbitmq management plugin

# Celery worker
  worker:
    image: productimporter_django:latest
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile-dev
    command: /run-celeryworker.sh
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=mysecretpass
      - POSTGRES_DB=product
      - USE_DOCKER=yes
    links:
      - postgres
      - rabbit
    depends_on:
      - django

# Celery beat
  scheduler:
    image: productimporter_django:latest
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile-dev
    command: /run-celerybeat.sh
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=mysecretpass
      - POSTGRES_DB=product
      - USE_DOCKER=yes
    links:
      - postgres
      - rabbit
    depends_on:
      - django
