# Generated by Django 3.0 on 2021-07-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210725_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploader',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
