FROM python:3.6
ENV PYTHONUNBUFFERED 1
ENV DJANGO_READ_DOT_ENV_FILE=False
ENV DJANGO_SETTINGS_MODULE=config.settings.local
ENV DEST_PATH=dist_dev

ARG DEBIAN_FRONTEND=noninteractive

# Install spatial libraries to work with Postgis and Geodjango
RUN apt-get update && \
		apt-get install -y --no-install-recommends \
		binutils \
		libproj-dev \
		gdal-bin \
		python-gdal \
		gettext



# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./compose/django/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

COPY ./compose/django/gunicorn.sh /gunicorn.sh
RUN sed -i 's/\r//' /gunicorn.sh
RUN chmod +x /gunicorn.sh

COPY ./compose/django/run-celeryworker.sh /run-celeryworker.sh
RUN sed -i 's/\r//' /run-celeryworker.sh
RUN chmod +x /run-celeryworker.sh

COPY ./compose/django/run-celerybeat.sh /run-celerybeat.sh
RUN sed -i 's/\r//' /run-celerybeat.sh
RUN chmod +x /run-celerybeat.sh


# create unprivileged user for running celery workers
RUN adduser --disabled-password --gecos '' celeryuser

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
